#!/usr/bin/env perl
use strict;
use warnings;

sub alert {
    my ($type, $title, $content) = @_;
    system("notify-send -u $type -c \"$title\" \"$content\"");
}

my $HOUR = 3600;
my $GAP = 5 * 60;

my %games = (
    "dota2" => {
        "proc_name" => "dota2",
        "limit"     => 2 * $HOUR,
        "union"     => []
    },
);

my %status = ();

for (;;) {
    for my $name (keys %games) {
        my $game = $games{$name};
        my $pn = $game->{"proc_name"};
        $status{$name} += $GAP if (`pidof $pn` ne "");
    }
    for my $name (keys %games) {
        my $game = $games{$name};
        my $pn = $game->{"proc_name"};
        if (`pidof $pn` ne "") {
            if (sub {
                    my $s = 0;
                    for my $k (@_) { $s += $k; }
                    return $s;
                }->(map { ($status{$_} // 0) } @{$game->{"union"}}) + $status{$name} > $game->{"limit"}) {
                alert("critical", "Limit exceeded", "Daily limit of $name exceeded.");
            }
        }
    }
    my $day = `date +%d`;
    sleep $GAP;
    %status = () if (`date +%d` ne $day);
}
